name: PR internal test comment trigger

on:
  issue_comment:
    # "Every pull request is an issue, but not every issue is a pull request."
    # - limit to PRs only in jobs: below
    types:
      - created # new comments only - no edits or deletions
      # - edited
      # - deleted
  
env:
  TEST_LIST: ${{ secrets.INTERNAL_TEST_LIST }}

jobs:
  pr_internal_test_comment_trigger2:
    name: PR internal test comment trigger2
    runs-on: ubuntu-latest
    steps:
      - name: think of a name
        run: |
          echo user: ${{ github.event.comment.user.login }}
          echo body: ${{ github.event.comment.body }}
          echo list: ${{ env.TEST_LIST }}
          #echo "test_list=${{ env.TEST_LIST }}" >> $GITHUB_OUTPUT
          echo "test_list=TRUE" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

jobs:
  pr_internal_test_comment_trigger:
    # Job runs for:
    # * new comments only
    # * PR comments only (Issue comments are skipped - see 'issue_comment:' above)
    # * comments from a specific user only
    # * specific comment-body content only (e.g. "/verify")
    #   - note: it is also possible to trigger on comment-body substrings with:
    #           contains(github.event.comment.body, 'substring')
    # * open PRs only
    # Requires:
    # * Github's 'gh' cli must be available on runner
    name: PR internal test comment trigger
    needs: pr_internal_test_comment_trigger2
    if: ${{ github.event.issue.pull_request && (github.event.comment.user.login == 'alan-forbes-cp') && (github.event.comment.body == '/verify') && (needs.pr_internal_test_comment_trigger2.outputs.test_list == 'TRUE) }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check PR status and obtain associated repo ref
        id: PR_REF
        run: |
          STATE=$(gh pr view $PR_NUMBER --repo $GH_REPO --json state --jq .state)
          if [ "$STATE" != "OPEN" ]; then
            echo "PR is not open - quitting ..."
            exit 1
          fi
          echo "PR is open ..."
          echo "pr_ref=$(gh pr view $PR_NUMBER --repo $GH_REPO --json headRefOid | jq -r '.headRefOid')" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
      - name: Add comment with internal test request data
        run: |
          gh issue comment "$PR_NUMBER" --body "$BODY"
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          BODY: >
            ${{ github.event.comment.body }}
            ${{ steps.PR_REF.outputs.pr_ref }}
            ${{ github.event.comment.user.login }}
      - name: Example build 1 - checkout PR ref
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ steps.PR_REF.outputs.pr_ref }}
      - name: Example build 2 - list latest commit and repo content
        run: |
          git log -1
          ls -l
