name: comment triggers pipeline
on:
  issue_comment:
    types:
      - created
      - edited
      - deleted
  
jobs:
  open_pr_commented:
    # This job only runs for open pull request comments
    # BUT ... is gh cli available on self hosted runners??
    name: Open PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          STATE=$(gh pr view $NUMBER --repo ${{ github.repository }} --json state --jq .state)
          if [ "$STATE" != "OPEN" ]; then
            echo "Cannot build for closed PRs"
            exit 1
          fi
          echo A comment on OPEN PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
          # Token needed for gh CLI
          GH_TOKEN: ${{ github.token }}

  issue_specific_comment:
    # This job only runs for specific issue comments
    name: Specific issue comment
    if: ${{ !github.event.issue.pull_request && github.event.comment.body == '/build' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A specific comment on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}

  issue_contains_comment:
    # This job only runs for issue contains comments
    name: Issue contains comment
    if: ${{ !github.event.issue.pull_request && contains(github.event.comment.body, 'string') }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A contains comment on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}

  issue_commented:
    # This job only runs for issue comments that dont match strings
    name: Non-matching issue comment
    if: ${{ !github.event.issue.pull_request && !(github.event.comment.body == '/build') && !(contains(github.event.comment.body, 'string')) }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A non-match comment on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}

