name: comment triggers pipeline
on:
  issue_comment:
    types:
      - created
      - edited
      - deleted
  
jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}

  issue_specific_comment:
    # This job only runs for specific issue comments
    name: Specific issue comment
    if: ${{ !github.event.issue.pull_request && github.event.comment.body == '/build' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A specific comment on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}

  issue_contains_comment:
    # This job only runs for issue contains comments
    name: Issue contains comment
    if: ${{ !github.event.issue.pull_request && contains(github.event.comment.body, 'string' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A contains comment on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}

  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request && !github.event.comment.body == '/build' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}

