name: PR comment trigger

on:
  issue_comment:
    # applies to both issues and PRs - limit to PRs only in jobs below
    types:
      - created # new comments only - no edits or deletions
      # - edited
      # - deleted
  
jobs:
  pr_comments:
    # Job runs for:
    # * new comments only
    # * PR comments only (Issue comments are skipped - see 'issue_comment:' above)
    # * comments from a specific user only
    # * specific comment-body content only ("/verify")
    #   - note: it is also possible to trigger on comment-body substrings with:
    #           contains(github.event.comment.body, 'substring')
    # * open PRs only
    # Requires:
    # * GH cli must be available on runner
    name: PR comments
    if: ${{ github.event.issue.pull_request && (github.event.comment.user.login == 'alan-forbes-cp') && (github.event.comment.body == '/verify') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check PR status and get associated repo ref
        id: PR_REF
        run: |
          STATE=$(gh pr view $PR_NUMBER --repo $GH_REPO --json state --jq .state)
          if [ "$STATE" != "OPEN" ]; then
            echo "PR is not open - quitting ..."
            exit 1
          fi
          echo "PR is open ..."
          echo "pr_ref=$(gh pr view $PR_NUMBER --repo $GH_REPO --json headRefOid | jq -r '.headRefOid')" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
      - name: Example build - checkout PR ref
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ steps.PR_REF.outputs.pr_ref }}
      - name: Example build - list latest commit and content
        run: |
          git log -1
          ls -l
      - name: Update comment
        permissions:
          issues: write
        run: |
          gh issue comment "$NUMBER" -- body "$BODY"
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          BODY: >
            /verify
            ${{ steps.PR_REF.outputs.pr_ref }}
