name: comment triggers pipeline
on:
  issue_comment:
    types:
      - created
      - edited
      - deleted
# also state the following to limit to PR openings??
#  pull_request:
#      - opened
  
jobs:
  open_pr_commented:
    # This job only runs for open pull request comments
    # BUT ... is gh cli available on self hosted (i.e. all) runners??
    name: Open PR comment
    if: ${{ github.event.issue.pull_request && (github.event.comment.user.login == 'Xalan-forbes-cp') }}
    #if: ${{ github.event.issue.pull_request }}
    #if: ${{ github.event.comment.user.login == 'alan-forbes-cp' }}
    runs-on: ubuntu-latest
    steps:
      - name: check PR status
        run: |
          STATE=$(gh pr view $NUMBER --repo ${{ github.repository }} --json state --jq .state)
          if [ "$STATE" != "OPEN" ]; then
            echo "Cannot build for closed PRs"
            exit 1
          fi
          echo GITHUB_SHA: $GITHUB_SHA
        env:
          NUMBER: ${{ github.event.issue.number }}
          # Token needed for gh CLI
          GH_TOKEN: ${{ github.token }}
      - name: get PR ref
        id: getRef
        run: |
          echo "pr_ref=$(gh pr view $NUMBER --repo ${{ github.repository }} --json headRefOid | jq -r '.headRefOid')" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
        env:
          NUMBER: ${{ github.event.issue.number }}
          # Token needed for gh CLI
          GH_TOKEN: ${{ github.token }}
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ steps.getRef.outputs.pr_ref }}
      - name: do build stuff
        if: ${{ github.event.comment.body == '/build' }}
        run: |
          echo A build comment on OPEN PR $NUMBER
          ls -l
        env:
          NUMBER: ${{ github.event.issue.number }}
      - name: do non-build stuff
        if: ${{ !(github.event.comment.body == '/build') }}
        run: |
          echo A non-build comment on OPEN PR $NUMBER
          ls -l
        env:
          NUMBER: ${{ github.event.issue.number }}

  issue_specific_comment:
    # This job only runs for specific issue comments
    name: Specific issue comment
    if: ${{ !github.event.issue.pull_request && github.event.comment.body == '/build' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A specific comment on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}

  issue_contains_comment:
    # This job only runs for issue contains comments
    name: Issue contains comment
    if: ${{ !github.event.issue.pull_request && contains(github.event.comment.body, 'string') }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A contains comment on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}

  issue_commented:
    # This job only runs for issue comments that dont match strings
    name: Non-matching issue comment
    if: ${{ !github.event.issue.pull_request && !(github.event.comment.body == '/build') && !(contains(github.event.comment.body, 'string')) }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A non-match comment on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}

